version: "3.9"
services:
  frontend:
    image: mysure/front:latest
    restart: always
    build:
      context: ./client/
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: "http://localhost/api" 
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  backend:
    image: mysure/back:latest
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    env_file:
      - .env
